### PR TITLE
Zeeshan fe dialog poll 23

### PR DESCRIPTION
**Pull request by sk-izsk**
polls dialog using react dropzone (#23 )

polls modal

### CODE REVIEW

**Review by aeciorc — COMMENTED** [review]
Looks great Zeeshan. One more thing to add: we want require that the user uploads exactly 2 images, since the polls is to compare two items. It could either be by dropping 2 images to that drop area, or having two drop areas, one for each image. What are your thoughts?

**Review by TheAllen — COMMENTED** [review]
Looks good. I like your implementation of PollsModal

**Comment by sk-izsk** [comment]
> Looks great Zeeshan. One more thing to add: we want require that the user uploads exactly 2 images, since the polls is to compare two items. It could either be by dropping 2 images to that drop area, or having two drop areas, one for each image. What are your thoughts?

Thanks a lot  @aeciorc I think we should have the same ui ... and during image selection we will choose two photos at the same time. anyway I already enable multi photo selection so this shouldn't be an issue IMO??

**Comment by sk-izsk** [comment]
> Looks good. I like your implementation of PollsModal

Thanks, man, much appreciated.

**Comment by aeciorc** [comment]
> > Looks great Zeeshan. One more thing to add: we want require that the user uploads exactly 2 images, since the polls is to compare two items. It could either be by dropping 2 images to that drop area, or having two drop areas, one for each image. What are your thoughts?
> 
> Thanks a lot @aeciorc I think we should have the same ui ... and during image selection we will choose two photos at the same time. anyway I already enable multi photo selection so this shouldn't be an issue IMO??

Yeas let's do that. Although we still need to ensure the user uploads exactly 2 images

**Review by aeciorc — APPROVED** [review]

**Pull request merged**
