### PR TITLE
Connected database to application

### PR DESCRIPTION
**Pull request by SsaaaadD2**
What it does
-Connects the application to MongoDB Atlas using a username and password stored in the .env file
-Exits the application if database cannot be connected, and outputs the error message.

What to look for
server/db/db.js
modified the server/bin/www file

### CODE REVIEW

**Review by TheAllen — COMMENTED** [review]
These implementations look good to me!

**Review by aeciorc — APPROVED** [review]
Looks good! Since we're ignoring the .env file, I think it would be a good idea to add a file called ".env.template" containing all the keys in the .env with empty values. This way we can keep tab of which env vars are needed by the app

**Comment by SsaaaadD2** [comment]
> Looks good! Since we're ignoring the .env file, I think it would be a good idea to add a file called ".env.template" containing all the keys in the .env with empty values. This way we can keep tab of which env vars are needed by the app

Sounds good, I've added the .env.template file with the two required database keys (without the values)

**Comment by aeciorc** [comment]
Great, feel free to merge this now

**Pull request merged**
